version: '3.8'

services:
  jupyter:
    image: jupyter/base-notebook
    # image: tensorflow:latest-gpu-jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./src:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
